content:
  - name: Accueil
    path: index.md
    type: file
    fields:
      - name: title
        type: string
      - name: layout
        type: string
        default: main.njk
        hidden: true
      - name: date
        type: date
      - name: heading
        type: string
      - name: subheading
        type: string
      - name: intro
        type: text
      - name: list_intro
        type: string
      - name: workshop_list
        type: object
        list: true
        fields:
          - name: date
            type: string
          - name: title
            type: string
          - name: url
            type: string
          - name: adresse
            type: string
      - name: extro
        type: text
      - name: body
        type: text
  - name: Template
    path: _include/main.njk
    type: file
    fields:
      - name: layout
        type: string
        default: html.njk
        hidden: true
      - name: main_url
        type: string
      - name: body
        type: text